name: api_creator
description: this desktop helps you to create API with in a seconds using node js , express and mongoose

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  path_provider: ^2.0.13
  talker_flutter: ^2.4.3
  percent_indicator: ^4.2.3
  connectivity_plus: ^3.0.3
  intl: ^0.17.0
  rename: ^2.1.1
  flutter_launcher_icons: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  msix: ^3.9.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/config/

  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/fonts/orbitron/Orbitron-Black.ttf
        - asset: assets/fonts/orbitron/Orbitron-Bold.ttf
        - asset: assets/fonts/orbitron/Orbitron-Regular.ttf
    - family: EncodeSansSC_Condensed
      fonts:
        - asset: assets/fonts/encode/EncodeSansSC_Condensed-Light.ttf
        - asset: assets/fonts/encode/EncodeSansSC_Condensed-Medium.ttf
        - asset: assets/fonts/encode/EncodeSansSC_Condensed-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_logo.png"
  windows:
    generate: true
    image_path: "assets/icon/app_logo.png"
msix_config:
  display_name: API-Creator
  publisher_display_name: Muhammad Fuzail Zaman
  identity_name: api-creator-001
  msix_version: 1.0.0.0
  languages: en-us
  capabilities: "internetClient"
  logo_path: "assets/icon/app_logo.png"
